[package]
name = "resume_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
genpdf = "0.2.0"
prompted = "0.2.8"
serde = { version = "1.0.217", features = [ "serde_derive", "derive" ] }
serde_json = "1.0.137"
